export const ABOUT_START = 'AUTH_START';
export const INNOVATION_START = 'AUTH_START';

export const SIDE_DRAWER_CONTROL = 'SIDE_DRAWER_CONTROL';
export const SHOW_DRAWER_TOGGLE = 'SHOW_DRAWER_TOGGLE';
export const MOVE_TO_HOME_PAGE = 'MOVE_TO_HOME_PAGE';