export const SIDE_DRAWER_CONTROL = 'SIDE_DRAWER_CONTROL';
export const SHOW_DRAWER_TOGGLE = 'SHOW_DRAWER_TOGGLE';
export const MOVE_TO_HOME_PAGE = 'MOVE_TO_HOME_PAGE';

export const AUTHENTICATED = 'AUTHENTICATED';
